language: ruby
cache: bundler
install:
- bundle install
script: ./cibuild.sh
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _site
    target_branch: master
    on:
        branch: source
env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
