# Site Metadata
title: Stevie Oberg
email: hi@steviecreates.com
description: >-
    Coder. Writer. Creator.
url: "http://www.steviecreates.com/"
twitter: stevieoberg

# Site Settings
collections:
  posts:
    output: true
defaults:
    - values:
        layout: default
    - scope:
        path: "_posts"
      values:
        layout: post

# Build settings
pre-commit:
    - check: FrontMatterVariableExists
      variables: ['description', 'image']
    - check: FrontMatterVariableIsNotDuplicate
      variables: ['description']
    - check: FrontMatterVariableMeetsLengthRequirements
      variables: ['description', 'title']
    - check: NoDuplicateTags

markdown: kramdown
plugins:
    - jekyll-feed

include:
    - _pages
exclude:
    - README.md
    - Rakefile
    - Gemfile
    - Gemfile.lock
    - changelog.md
    - "*.Rmd"
    - vendor
    - .travis.yml
