# Site settings
title: Stevie Oberg
email: hi@steviecreates.com
description: >-
    Writer. Coder. Creator.
url: "http://www.steviecreates.com"
twitter: sgtoctopus
github: sgtoctopus

collections:
    projects:
        output: true
        permalink: /projects/:path/

# Build settings
markdown: kramdown
plugins:
    - jekyll-feed
