# Site settings
title: Stevie Oberg
email: hi@steviecreates.com
description: >-
    Writer. Coder. Creator.
url: "http://www.steviecreates.com/"
twitter: stevieoberg
github: stevieoberg

destination: ../_site

collections:
    projects:
        title: Projects
        output: true
        icon: "fas fa-terminal"
    art:
        title: Art
        output: true
        icon: "fas fa-paint-brush"
    posts:
        title: Blog
        output: false

defaults:
    - scope:
        path: "_projects"
      values:
        layout: project
    - scope:
        path: "_art"
      values:
        layout: art
    - scope:
        path: "_posts"
      values:
        layout: post

# Build settings
markdown: kramdown
plugins:
    - jekyll-feed

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
